# Generated by Django 6.0.6 on 2026-07-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0002_rename_product_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
